repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace


-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3


#-   repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: v0.0.40
#    hooks:
#      - id: lint


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ --fix=lf ]
        args: [ --fix=auto ]
